baseURL = "https://c2020.maoyachen.com/"
languageCode = "zh-cn"
title = "C程序设计2020秋季学期"
paginate = 3
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[author]
name = "毛亚琛"
abstract = "Hello World!"
url = "https://maoyachen.com"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
